# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addbooks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x64\x64\x62ooks.proto\x12\x08tutorial\"/\n\x0b\x41\x64\x64ressBook\x12 \n\x06people\x18\x01 \x03(\x0b\x32\x10.tutorial.Person\"\x9f\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x02\x12\x13\n\x0bwork_status\x18\x05 \x01(\x08\x12%\n\x06phones\x18\x06 \x03(\x0b\x32\x15.tutorial.PhoneNumber\x12!\n\x04maps\x18\x07 \x01(\x0b\x32\x13.tutorial.MyMessage\"@\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.tutorial.PhoneType\"q\n\tMyMessage\x12\x33\n\x08mapfield\x18\x01 \x03(\x0b\x32!.tutorial.MyMessage.MapfieldEntry\x1a/\n\rMapfieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01*+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addbooks_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYMESSAGE_MAPFIELDENTRY._options = None
  _MYMESSAGE_MAPFIELDENTRY._serialized_options = b'8\001'
  _PHONETYPE._serialized_start=420
  _PHONETYPE._serialized_end=463
  _ADDRESSBOOK._serialized_start=28
  _ADDRESSBOOK._serialized_end=75
  _PERSON._serialized_start=78
  _PERSON._serialized_end=237
  _PHONENUMBER._serialized_start=239
  _PHONENUMBER._serialized_end=303
  _MYMESSAGE._serialized_start=305
  _MYMESSAGE._serialized_end=418
  _MYMESSAGE_MAPFIELDENTRY._serialized_start=371
  _MYMESSAGE_MAPFIELDENTRY._serialized_end=418
# @@protoc_insertion_point(module_scope)
