# Generated by Django 3.2.6 on 2023-08-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minixr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=160)),
                ('target_photo', models.ImageField(upload_to='photos/')),
                ('model_url', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
