# Generated by Django 3.2.6 on 2023-08-23 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minixr', '0002_auto_20230823_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrmaterials',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
